# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 23:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='name',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='overall_sitter_rank',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='ratings_score',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='sitter_score',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='rating',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
