# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0002_auto_20171006_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='name',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='overall_sitter_rank',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='ratings_score',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='sitter_score',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
