# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0004_auto_20171007_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='sitter_score',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
