# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0006_auto_20171007_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='dogs',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
